apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-bot
  namespace: crt-nshift-lightspeed-tenant
subjects:
- kind: ServiceAccount
  name: release-bot
  apiGroup: ""
roleRef:
  kind: Role
  name: release-bot
  apiGroup: rbac.authorization.k8s.io


