apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-bundle-related-images
spec:
  params:
    - name: snapshot
      type: string
    - name: release
      type: string
    - name: gitUrl
      type: string
      default: "https://github.com/raptorsun/lightspeed-operator.git"
    - name: branch
      type: string
      default: "bundle-update"
  tasks:
    - name: update-related-images
      taskSpec:
        params:
          - name: gitUrl
            type: string
          - name: branch
            type: string
          - name: snapshot
            type: string
          - name: release
            type: string
        steps:
          - name: git-clone
            image: docker.io/raptorsun/bundle-update:0.0.1
            script: |
              # todo: remove the hardcoded branch
              git clone --single-branch --branch main $(params.gitUrl) repo
              cd repo
              git checkout -b $(params.branch)
            workingDir: /workspace/source
            env:
              - name: HOME
                value: /workspace/source
          - name: update-file
            image: docker.io/raptorsun/bundle-update:0.0.1
            script: |
              oc login --token=${KONFLUX_TOKEN} --server=https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
              IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
              SNAPSHOT_IMAGES=$(oc get snapshot "$(params.snapshot)" -n "$RELEASE_NAMESPACE" \
              -o jsonpath='{.spec.components}')
              echo "Snapshot images: $SNAPSHOT_IMAGES"
              cd repo
              # todo: remove the hardcoded bundle reference
              ./hack/snapshot_to_image_list.sh -s "$(params.snapshot)" -b ols-bundle-8k8gd -r stable -o related_images.json
            workingDir: /workspace/source
            env:
              - name: KONFLUX_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: release-bot-konflux-token
                    key: konflux-token
              - name: HOME
                value: /workspace/source
          - name: git-config
            image: docker.io/raptorsun/bundle-update:0.0.1
            script: |
              cd repo
              git config user.email "hasun@redhat.com"
              git config user.name "Haoyu Sun's Bot"
            workingDir: /workspace/source
            env:
              - name: HOME
                value: /workspace/source
          - name: git-commit-push
            image: docker.io/raptorsun/bundle-update:0.0.1
            workingDir: /workspace/source
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: release-bot-github-token
                    key: github-token
              - name: HOME
                value: /workspace/source
            script: |
              cd repo
              git add related_images.json
              git commit -m "Update related_images with snapshot $(params.snapshot)"
              git rev-parse HEAD | tee $(results.commit-id.path)
              git config --global credential.helper '!f() { sleep 1; echo "username=git"; echo "password=$GITHUB_TOKEN"; }; f'
              git push --force origin $(params.branch)
              # todo: remove the hardcoded PR title, body, and head fork name
              RESPONSE=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${GITHUB_TOKEN}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/openshift/lightspeed-operator/pulls \
                -d '{"title":"[Do Not Merge] Test Konflux Bundle Update Snapshot $(params.snapshot)","body":"Do not merge!","head":"raptorsun:$(params.branch)","base":"main"}' )
              echo "Github response: \n $RESPONSE"
              jq -r '.html_url' <<< $RESPONSE | tee $(results.pull-request-url.path)
        results:
          - name: commit-id
            description: The commit ID where bundle is updated
          - name: pull-request-url
            description: The URL of the created pull request
      params:
        - name: gitUrl
          value: $(params.gitUrl)
        - name: branch
          value: $(params.branch)
        - name: snapshot
          value: $(params.snapshot)
        - name: release
          value: $(params.release)
      workspaces:
        - name: source
  workspaces:
    - name: source
  results:
    - name: commit-id
      description: The commit ID where bundle is updated
      value: "$(tasks.update-related-images.results.commit-id)"
    - name: pull-request-url
      description: The URL of the created pull request
      value: "$(tasks.update-related-images.results.pull-request-url)"
