apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-bundle-related-images
spec:
  params:
    - name: snapshot
      type: string
    - name: release
      type: string
    - name: url
      type: string
      default: "https://github.com/raptorsun/lightspeed-operator.git"
    - name: branch
      type: string
      default: "bundle-update"
  tasks:
    - name: update-related-images
      taskSpec:
        params:
          - name: url
            type: string
          - name: branch
            type: string
          - name: snapshot
            type: string
        steps:
          - name: git-clone
            image: alpine/git
            script: |
              git clone --single-branch --branch main $(params.url) repo
              cd repo
              git checkout -b $(params.branch)
            workingDir: /workspace/source
          - name: update-file
            image: alpine
            script: |
              ls
              echo "$(params.snapshot)" > repo/related_images
            workingDir: /workspace/source
          - name: git-config
            image: alpine/git
            script: |
              cd repo
              git config user.email "hasun@redhat.com"
              git config user.name "Haoyu Sun's Bot"
            workingDir: /workspace/source
          - name: git-commit-push
            image: alpine/git
            workingDir: /workspace/source
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: release-bot-github-token
                    key: github-token
            script: |
              cd repo
              git add related_images
              git commit -m "Update related_images with snapshot $(params.snapshot)"
              git rev-parse HEAD | tee $(results.commit-id.path)
              git config --global credential.helper '!f() { sleep 1; echo "username=git"; echo "password=$GITHUB_TOKEN"; }; f'
              git push --force origin $(params.branch)
        results:
          - name: commit-id
            description: The commit ID where bundle is updated
      params:
        - name: url
          value: $(params.url)
        - name: branch
          value: $(params.branch)
        - name: snapshot
          value: $(params.snapshot)
      workspaces:
        - name: source
  workspaces:
    - name: source
  results:
    - name: commit-id
      description: The commit ID where bundle is updated
      value: "$(tasks.update-related-images.results.commit-id)"
