apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: update-bundle-related-images
spec:
  params:
    - name: snapshot
      type: string
    - name: release
      type: string
    - name: gitUrl
      type: string
      default: "https://github.com/raptorsun/lightspeed-operator.git"
    - name: branch
      type: string
      default: "bundle-update"
  tasks:
    - name: update-related-images
      taskSpec:
        params:
          - name: gitUrl
            type: string
          - name: branch
            type: string
          - name: snapshot
            type: string
          - name: release
            type: string
        steps:
          - name: git-clone
            image: alpine/git
            script: |
              git clone --single-branch --branch main $(params.gitUrl) repo
              cd repo
              git checkout -b $(params.branch)
            workingDir: /workspace/source
          - name: update-file
            image: registry.access.redhat.com/ubi9/ubi-minimal
            script: |
              curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest-4.19/openshift-client-linux-amd64-rhel9.tar.gz \
                  && tar -xvzf oc.tar.gz \
                  && chmod +x kubectl oc \
                  && mv oc kubectl /usr/local/bin/
              oc version
              IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
              RELEASE_CONDITIONS=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" \
              -o jsonpath='{.status.conditions}' | jq '.[] | select(.type == "ManagedPipelineProcessed")')
              echo "Release conditions: $RELEASE_CONDITIONS"
              SNAPSHOT_IMAGES=$(kubectl get snapshot "$(params.snapshot)" -n "$RELEASE_NAMESPACE" \
              -o jsonpath='{.spec.components}')
              echo "Snapshot images: $SNAPSHOT_IMAGES"
              

            workingDir: /workspace/source
            env:
              - name: KONFLUX_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: release-bot-konflux-token
                    key: konflux-token
          - name: git-config
            image: alpine/git
            script: |
              cd repo
              git config user.email "hasun@redhat.com"
              git config user.name "Haoyu Sun's Bot"
            workingDir: /workspace/source
          - name: git-commit-push
            image: alpine/git
            workingDir: /workspace/source
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: release-bot-github-token
                    key: github-token
            script: |
              cd repo
              git add related_images
              git commit -m "Update related_images with snapshot $(params.snapshot)"
              git rev-parse HEAD | tee $(results.commit-id.path)
              git config --global credential.helper '!f() { sleep 1; echo "username=git"; echo "password=$GITHUB_TOKEN"; }; f'
              git push --force origin $(params.branch)
        results:
          - name: commit-id
            description: The commit ID where bundle is updated
      params:
        - name: gitUrl
          value: $(params.gitUrl)
        - name: branch
          value: $(params.branch)
        - name: snapshot
          value: $(params.snapshot)
        - name: release
          value: $(params.release)
      workspaces:
        - name: source
  workspaces:
    - name: source
  results:
    - name: commit-id
      description: The commit ID where bundle is updated
      value: "$(tasks.update-related-images.results.commit-id)"
